/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gestor_de_proyectos.interfaces;

import AccesoDatos.Categorias;
import AccesoDatos.Entity_Main;
import AccesoDatos.IngresoEgreso;
import AccesoDatos.UnidadesDeMedida;
import Controladores.CategoriasJpaController;
import Controladores.IngresoEgresoJpaController;
import Controladores.UnidadesDeMedidaJpaController;
import java.awt.Color;
import java.math.BigDecimal;
import java.math.BigInteger;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author josse
 */
public class ViewDetalles_Proyecto extends javax.swing.JFrame {

    /**
     * Creates new form Detalles_Proyecto
     */
    public ViewDetalles_Proyecto() {
        this.getContentPane().setBackground(new Color(153,168,178));
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNombre = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        cmbFiltro = new javax.swing.JComboBox<>();
        lblGasto = new javax.swing.JLabel();
        lblIngreso = new javax.swing.JLabel();
        lblBalance = new javax.swing.JLabel();
        btnReporte = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnNuevo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblNombre.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblNombre.setText("Proyecto: ");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Filtro:");

        cmbFiltro.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cmbFiltro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos", "Egresos", "Ingresos", "Pérdida mercancía" }));

        lblGasto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblGasto.setText("Gasto: $");

        lblIngreso.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblIngreso.setText("Ingreso: $");

        lblBalance.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblBalance.setText("Balance: $");

        btnReporte.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnReporte.setText("Reporte");

        jTable1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "#", "Descripción", "Tipo", "Fecha", "Categoría", "Cantidad", "Medida", "Monto", "null"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        btnNuevo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnNuevo.setText("Nuevo registro");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(434, 434, 434)
                        .addComponent(lblNombre)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmbFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(94, 94, 94)
                        .addComponent(lblGasto)
                        .addGap(69, 69, 69)
                        .addComponent(lblIngreso)
                        .addGap(80, 80, 80)
                        .addComponent(lblBalance)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 116, Short.MAX_VALUE)
                        .addComponent(btnNuevo)
                        .addGap(18, 18, 18)
                        .addComponent(btnReporte)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(lblNombre)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cmbFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblGasto)
                    .addComponent(lblIngreso)
                    .addComponent(lblBalance)
                    .addComponent(btnReporte)
                    .addComponent(btnNuevo))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 369, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        IngresoEgresoJpaController ctrlIngreso = new IngresoEgresoJpaController(Entity_Main.getInstance(), this);
        ctrlIngreso.CrearRegistro();
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        IngresoEgresoJpaController ctrlIngreso = new IngresoEgresoJpaController(Entity_Main.getInstance(), this);
        Categorias _categorias = new Categorias();
        UnidadesDeMedida _unidades = new UnidadesDeMedida();
        int fila = jTable1.getSelectedRow();
        int columna = jTable1.getSelectedColumn();
        if (columna == 8) {
            SimpleDateFormat objSDF = new SimpleDateFormat("dd-MM-yyyy");
            Date fecha = null;
            String status;
            IngresoEgreso _ingresoEgreso = new IngresoEgreso();
            _ingresoEgreso.setIeId(BigDecimal.valueOf(Double.parseDouble(jTable1.getValueAt(fila, 0).toString())));
            _ingresoEgreso.setIeDescripcion(jTable1.getValueAt(fila, 1).toString());
            if (jTable1.getValueAt(fila, 2).toString().equals("Ingreso")) {
                status = "0";
                _ingresoEgreso.setIeTipo(new BigInteger(String.valueOf(status)));
            }
            else{
                status = "1";
                _ingresoEgreso.setIeTipo(new BigInteger(String.valueOf(status)));
            }
            try {
                fecha = objSDF.parse(jTable1.getValueAt(fila, 3).toString());
                _ingresoEgreso.setIeFecha(fecha);
            } catch (ParseException e) {
                JOptionPane.showMessageDialog(this, e.getMessage());
            }
            
            _ingresoEgreso.setCatId(buscarCategoriaID(jTable1.getValueAt(fila, 4).toString()));
            _ingresoEgreso.setIeCantidad(Double.parseDouble(jTable1.getValueAt(fila, 5).toString()));
            _ingresoEgreso.setUmId(buscarMedidaID(jTable1.getValueAt(fila, 6).toString()));
            _ingresoEgreso.setIeMonto(Double.parseDouble(jTable1.getValueAt(fila, 7).toString()));
            _ingresoEgreso.setIeCalidad(BigInteger.valueOf(Long.parseLong(ctrlIngreso.buscarCalidadID(Integer.parseInt(jTable1.getValueAt(fila, 0).toString())))));
            ctrlIngreso.leerTabla(_ingresoEgreso);
        }
    }//GEN-LAST:event_jTable1MouseClicked

    Categorias _categorias = new Categorias();
    
    public Categorias buscarCategoriaID(String categoria) {
        CategoriasJpaController ctrlCategorias= new CategoriasJpaController(Entity_Main.getInstance());
        ArrayList<Categorias> lst = new ArrayList<Categorias>();
        lst = ctrlCategorias.findSearch(categoria);
        if (lst.size() > 0) {
            _categorias.setCatId(lst.get(0).getCatId());
            _categorias.setCatNombre(lst.get(0).getCatNombre());
            _categorias.setCatTipo(lst.get(0).getCatTipo());
        }
        return _categorias;
    }
    
    UnidadesDeMedida _unidades = new UnidadesDeMedida();
    
    public UnidadesDeMedida buscarMedidaID(String medida) {
        UnidadesDeMedidaJpaController ctrlUnidades = new UnidadesDeMedidaJpaController(Entity_Main.getInstance());
        ArrayList<UnidadesDeMedida> lst = new ArrayList<UnidadesDeMedida>();
        lst = ctrlUnidades.findUnidadSearch(medida);
        if (lst.size() > 0) {
            _unidades.setUmId(lst.get(0).getUmId());
            _unidades.setUmNombre(lst.get(0).getUmNombre());
        }
        return _unidades;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewDetalles_Proyecto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewDetalles_Proyecto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewDetalles_Proyecto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewDetalles_Proyecto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewDetalles_Proyecto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnNuevo;
    public javax.swing.JButton btnReporte;
    public javax.swing.JComboBox<String> cmbFiltro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable jTable1;
    public javax.swing.JLabel lblBalance;
    public javax.swing.JLabel lblGasto;
    public javax.swing.JLabel lblIngreso;
    public javax.swing.JLabel lblNombre;
    // End of variables declaration//GEN-END:variables
}
